<?php

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;

// Serve the production React SPA built into backend/public/app (see root
// vite.config.js: base '/app/', outDir 'backend/public/app'). The bundle is
// generated by CI and is gitignored, so fall back to the welcome view when
// it is absent (e.g. fresh local checkout without a build).
Route::get('/app/{any?}', function () {
    $index = public_path('app/index.html');

    if (! File::exists($index)) {
        return view('welcome');
    }

    return response()->file($index);
})->where('any', '.*');

// Catch-all for any other non-API web route (deep links, landing pages):
// serve the SPA when built, otherwise the default welcome view. API routes
// (routes/api.php, prefixed api/*) and the /up health check never reach here.
Route::get('/{any}', function () {
    $index = public_path('app/index.html');

    if (! File::exists($index)) {
        return view('welcome');
    }

    return response()->file($index);
})->where('any', '^(?!api(?:/|$)|up$).*$');
