<?php

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;

// Serve the production React SPA built into backend/public/app (see root
// vite.config.js: base '/app/', outDir 'backend/public/app'). Matches every
// non-API path including '/' (deep links like /app/dashboard need index.html
// for the browser router). API routes (routes/api.php, prefixed api/*) and
// the /up health check never reach here. The bundle is generated by CI and is
// gitignored, so fall back to the welcome view when absent (e.g. fresh local
// checkout without a build).
Route::get('/{any?}', function () {
    $index = public_path('app/index.html');

    if (! File::exists($index)) {
        return view('welcome');
    }

    return response()->file($index);
})->where('any', '(?!api/|up$).*');
