import { useEffect, useState } from "react";
import { decideVerification, downloadVerificationDocument, fetchAdminReports, fetchVerificationQueue, resolveAdminReport } from "../lib/api";
import { useLanguage } from "../theme/LanguageProvider";

export default function AdminPage() {
  const { t } = useLanguage();
  const [reports, setReports] = useState([]); const [users, setUsers] = useState([]); const [error, setError] = useState("");
  const refresh = async () => { try { const [r, u] = await Promise.all([fetchAdminReports(), fetchVerificationQueue()]); setReports(r.data || []); setUsers(u.data || []); setError(""); } catch (e) { setError(e.response?.status === 403 ? "This account does not have administrator access." : "Sign in with an administrator account."); } };
  useEffect(() => { refresh(); }, []);
  const review = async (id, status) => { await resolveAdminReport(id, status); await refresh(); };
  const verify = async (id, status) => { await decideVerification(id, status); await refresh(); };
  const viewDocument = async (id) => { const tab = window.open("about:blank", "_blank", "noopener,noreferrer"); try { const url = await downloadVerificationDocument(id); if (tab) tab.location.href = url; window.setTimeout(() => URL.revokeObjectURL(url), 60000); } catch { tab?.close(); setError("Could not open the private ID document."); } };
  return <div className="mx-auto max-w-5xl space-y-8 p-5 md:p-8" style={{ color: "var(--theme-ink)" }}><header><p className="text-xs font-bold uppercase tracking-[.2em] opacity-60">Moderation</p><h1 className="mt-2 font-serif text-3xl font-black">{t("Admin review")}</h1><p className="mt-2 text-sm opacity-70">Review reported listings and account documents.</p></header>{error && <p role="alert" className="rounded-xl border border-amber-500/40 p-4 text-sm">{error}</p>}<section className="space-y-3"><h2 className="font-serif text-xl font-bold">{t("Listing reports")}</h2>{reports.map((report) => <article key={report.id} className="glass-pane flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4" style={{ borderColor: "var(--theme-border)" }}><div><strong>{report.reason}: {report.listing?.title}</strong><p className="text-sm opacity-70">{report.listing?.location} · by {report.user?.name} · {report.status}</p>{report.details && <p className="mt-1 text-sm">{report.details}</p>}</div><div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => review(report.id, "dismissed")}>{t("Dismiss")}</button><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => review(report.id, "removed")}>{t("Hide listing")}</button></div></article>)}{!error && !reports.length && <p className="text-sm opacity-60">No reports to review.</p>}</section><section className="space-y-3"><h2 className="font-serif text-xl font-bold">{t("Identity verification")}</h2>{users.map((person) => <article key={person.id} className="glass-pane flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4" style={{ borderColor: "var(--theme-border)" }}><div><strong>{person.name}</strong><p className="text-sm opacity-70">{person.email} · {person.phone || "No phone number"}</p></div><div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => viewDocument(person.id)}>{t("View document")}</button><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => verify(person.id, "verified")}>{t("Approve")}</button><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => verify(person.id, "rejected")}>{t("Reject")}</button></div></article>)}{!error && !users.length && <p className="text-sm opacity-60">No accounts waiting for verification.</p>}</section></div>;
}
