import { useState } from "react";
import { submitVerification } from "../lib/api";
import { useLanguage } from "../theme/LanguageProvider";

export default function VerificationPage() {
  const { t } = useLanguage();
  const [file, setFile] = useState(null); const [phone, setPhone] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const user = (() => { try { return JSON.parse(localStorage.getItem("toletmama.api_user") || "{}"); } catch { return {}; } })();
  const send = async (event) => { event.preventDefault(); setError(""); setMessage(""); try { const result = await submitVerification({ document: file, phone }); const updated = { ...user, verification_status: result.verification_status }; localStorage.setItem("toletmama.api_user", JSON.stringify(updated)); setMessage("Your document was submitted for review."); } catch (e) { setError(e.response?.data?.message || "Could not submit verification."); } };
  return <div className="mx-auto max-w-2xl space-y-5 p-5 md:p-8" style={{ color: "var(--theme-ink)" }}><header><p className="text-xs font-bold uppercase tracking-[.2em] opacity-60">Trust and safety</p><h1 className="mt-2 font-serif text-3xl font-black">{t("Verify your account")}</h1><p className="mt-2 text-sm opacity-70">Upload a student or owner ID for a human review. Documents are stored privately. Phone numbers are contact details; SMS verification is not enabled yet.</p></header><p className="rounded-xl border p-4 text-sm" style={{ borderColor: "var(--theme-border)" }}>Current status: <strong className="capitalize">{user.verification_status || "unverified"}</strong></p><form onSubmit={send} className="glass-pane space-y-4 rounded-2xl border p-5" style={{ borderColor: "var(--theme-border)" }}><label className="block space-y-2 text-sm">Phone number (optional)<input value={phone} onChange={e => setPhone(e.target.value)} className="w-full rounded-xl border bg-transparent p-3" style={{ borderColor: "var(--theme-border)" }} placeholder="+880 1..."/></label><label className="block space-y-2 text-sm">ID document (JPG, PNG, or PDF; max 5 MB)<input required type="file" accept="image/jpeg,image/png,application/pdf" onChange={e => setFile(e.target.files?.[0] || null)} className="block w-full text-sm"/></label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}{message && <p role="status" className="text-sm text-emerald-700">{message}</p>}<button className="rounded-xl px-4 py-2 font-bold" style={{ background: "var(--theme-ink)", color: "var(--theme-bg)" }}>{t("Submit for review")}</button></form></div>;
}
